namespace: ivory-operator

commonLabels:
  app.kubernetes.io/name: ivyo
  # The version below should match the version on the IvoryCluster CRD
  app.kubernetes.io/version: 5.3.2

bases:
- ../crd
- ../rbac/namespace
- ../manager

images:
- name: ivory-operator
  newName: docker.io/ivorysql/ivory-operator
  newTag: v5.0

patchesJson6902:
- target: { group: apps, version: v1, kind: Deployment, name: ivyo }
  path: selectors.yaml

patchesStrategicMerge:
- manager-target.yaml
